### ISSUE TITLE
Failed Install

### ISSUE THREAD

**Issue by InTheCloudDan** [lrills/helm-unittest#34]
Trying to install it in an Alpine container, hitting
```
[debug] cloning https://github.com/lrills/helm-unittest to /root/.helm/cache/plugins/https-github.com-lrills-helm-unittest
[debug] setting version to ""
[debug] symlinking /root/.helm/cache/plugins/https-github.com-lrills-helm-unittest to /root/.helm/plugins/helm-unittest
[debug] loading plugin from /root/.helm/plugins/helm-unittest
[debug] running install hook: &{/bin/sh [sh -c $HELM_PLUGIN_DIR/install-binary.sh] []  <nil> <nil> <nil> [] %!s(*syscall.SysProcAttr=<nil>) %!s(*os.Process=<nil>) <nil> <nil> <nil> %!s(bool=false) [] [] [] [] %!s(chan error=<nil>) %!s(chan struct {}=<nil>)}
Downloading
curl: (3) <url> malformed
Failed to install helm-unittest
\tFor support, go to https://github.com/kubernetes/helm.
```
Container does have curl, trying to find a way to do a set -x before the helm plugin install but it's not working as expected.

**Comment by lrills** [comment]
Hi, you can download the binaries from the release you want and install the plugin from local directory, dockerfile like below might work:
```dockerfile
# ...
ADD https://github.com/lrills/helm-unittest/releases/download/v0.1.2/helm-unittest-linux-0.1.2.tgz
RUN mkdir unittest && \
  tar -C unittest -zxvf helm-unittest-linux-0.1.2.tgz && \
  helm plugin install ./unittest

**Comment by walkafwalka** [comment]
Hey @InTheCloudDan and @benzvan, I am trying to revive this project since the maintainer seems to be gone. I also tried contacting him separately, but no response. If he comes back, I plan to submit any changes I make on my back to this one.

For this particular request, I fixed the example with this MR (https://gitlab.com/walkafwalka/helm-unittest/merge_requests/5) and it is included in the [0.2.1 release](https://gitlab.com/walkafwalka/helm-unittest/releases).

**Comment by mhuang0711** [comment]
Hi Irills @lrills , when I try to install helm-unittest, I still get the Error:  plugin install hook for "unittest" exited with error,  I have tried the binaries way, still doesn't work. Could you have a look at it? BTW, I'm using helm 3.

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
